= Couchbase Cluster with PetSet and PortWorx

. Start Kubernetes cluster:
+
```
export KUBERNETES_PROVIDER=aws
KUBE_OS_DISTRIBUTION=wily NODE_SIZE=m3.medium MASTER_SIZE=m3.medium ./cluster/kube-up.sh
```
+
.. Default distribution is Debian and had issues starting up Portworx container
. Create 4 EBS volumes using the command: `aws ec2 create-volume --region us-west-2 --availability-zone us-west-2a --volume-type io1 --iops 1000 --size 128`
. Get the volume ids: `vol-df734157`, `vol-ce734146`, `vol-ec734164`, `vol-cf734147`
. Get the instance ids for minions: `i-b27ee627`, `i-b37ee626`, `i-b47ee621`, `i-b57ee620`
. Make sure AWS CLI is configured correctly for `us-west-2` region: `aws configure`
. Attach a volume to each instance:
+
```
aws ec2 attach-volume --volume-id <volume-id> --instance-id <instance-id> --device /dev/sdf
```
+
For example:
```
aws ec2 attach-volume --volume-id vol-df734157 --instance-id i-b27ee627 --device /dev/sdk
aws ec2 attach-volume --volume-id vol-ce734146 --instance-id i-b37ee626 --device /dev/sdk
aws ec2 attach-volume --volume-id vol-ec734164 --instance-id i-b47ee621 --device /dev/sdk
aws ec2 attach-volume --volume-id vol-cf734147 --instance-id i-b57ee620 --device /dev/sdk
```
+
. Optional verification
.. Log in to minion: `ssh -i ~/.ssh/kube_aws_rsa admin@<master-ip-public>`
.. Verify etcd: `curl -fs -X PUT "http://<master-ip-internal>:2379/v2/keys/_test"`
. For each minion (because Kubernetes 1.4.5 uses 1.11.2, works OOTB on 1.12)
.. ssh minion: `ssh -i ~/.ssh/kube_aws_rsa admin@<public-ip>`
.. `sudo vi /lib/systemd/system/docker.service`
.. Comment `MountFlags=slave`
.. `sudo systemctl daemon-reload`
.. `sudo systemctl restart docker`
. On each host, start PWX container:
+
```
sudo docker run --restart=always --name px -d --net=host \
   --privileged=true \
   -v /run/docker/plugins:/run/docker/plugins \
   -v /var/lib/osd:/var/lib/osd:shared \
   -v /dev:/dev \
   -v /etc/pwx:/etc/pwx \
   -v /opt/pwx/bin:/export_bin \
   -v /usr/libexec/kubernetes/kubelet-plugins/volume/exec/px~flexvolume:/export_flexvolume:shared \
   -v /var/run/docker.sock:/var/run/docker.sock \
   -v /var/cores:/var/cores \
   -v /var/lib/kubelet:/var/lib/kubelet:shared \
   --ipc=host \
   portworx/px-enterprise -k etcd:http://etcd-us-east-1b.portworx.com:4001 -c couchbase_portworx2 -a -f
```
+
.

